### PR TITLE
Fix/token pool raw type

### LINKED ISSUE #245: [Enhancement]: Update Pool Type field
### What would you like us to improve?

regarding the pool type, could you please tell thisdot to just use the value of rawType as returned by the mock api?

### How important it is?

important

### PR DESCRIPTION
**Pull request by markshenouda**
image
image

## Closing issues

closes [#245](https://github.com/thisdot/chainlink-docs/issues/245)

### CODE REVIEW

File: src/components/CCIP/ChainHero/TokenDetailsHero.tsx [hunk 1]
```diff
@@ -1,7 +1,6 @@
 import Address from "~/components/AddressReact.tsx"
 import { getExplorerAddressUrl, fallbackTokenIconUrl } from "~/features/utils/index.ts"
 import { PoolType } from "~/config/data/ccip/types.ts"
-import { tokenPoolDisplay } from "~/config/data/ccip/utils.ts"
```
Comment (Zelig880) [inline src/components/CCIP/ChainHero/TokenDetailsHero.tsx:4]: The actual method was not removed! Please remove it as it is unused

**Review by Zelig880 — CHANGES_REQUESTED** [review]
